### ISSUE TITLE
Crash in 1.19.2 while running

### ISSUE THREAD

**Issue by Darwign** [P3pp3rF1y/SophisticatedCore#115]
I'm making a modpack  for myself and I would love to include Sophisticated Backpacks but it seems it crashes randomly for some reason., is it perhaps incompatible with Valhelsia mods ?

Crashlog: https://pastebin.com/h15jWUr7

**Comment by P3pp3rF1y** [comment]
you have outdated version of backpacks in the pack that is your issue. just update it as well
