### ISSUE TITLE
REI Not Recognizing the Crafting Upgrade (backpack and storage) as valid crafting tables.

### ISSUE THREAD

**Issue by docHP** [P3pp3rF1y/SophisticatedCore#131]
Title!
![image](https://github.com/P3pp3rF1y/SophisticatedCore/assets/44784448/dca57126-8681-4ed4-9071-42a6ac23ec63)

**Comment by P3pp3rF1y** [comment]
I don't have a compatibility with REI directly, only with JEI and JEI compat works correctly. REI has a JEI plugin that handles compat with mods like mine. 
Looking at this briefly I can't immediately see anything that I would be doing wrong so I suggest you follow up with REI on this as it seems like there's something wrong with their JEI plugin in this case. Also I can see another bug on their tracker for another issue with that plugin that involves sophisticated so probably more needs to be solved there.
