### ISSUE TITLE
Crash when loading game 1.19.4

### ISSUE THREAD

**Issue by Florydka** [P3pp3rF1y/SophisticatedCore#132]
[latest.log](https://github.com/P3pp3rF1y/SophisticatedCore/files/11991480/latest.log)
The game crashes when I try to open it. 
<img width="429" alt="image" src="https://github.com/P3pp3rF1y/SophisticatedCore/assets/139006637/e9e8cb63-5ad0-4ce1-8467-6af3a92573c4">
There is a problem with both sophisticated backpacks and the core.

**Comment by P3pp3rF1y** [comment]
that would be because you're trying to run 1.19.2 version in 1.19.4 that obviously isn't going to work. if you want to use sophisticated mods you have to choose either 1.19.2 or 1.20.1 version of forge / mods and play with that.

**Comment by Florydka** [comment]
> that would be because you're trying to run 1.19.2 version in 1.19.4 that obviously isn't going to work. if you want to use sophisticated mods you have to choose either 1.19.2 or 1.20.1 version of forge / mods and play with that.

ooooh, it worked for all other mods, thanks for help
