### ISSUE TITLE
random crash

### ISSUE THREAD

**Issue by CubeTwo** [P3pp3rF1y/SophisticatedCore#150]
sophisticatedcore-1.19.2-0.5.82.382
forge 43.2.21
dont know where put crash log, but seems its core
opened inventory and mouse to  item got random crash, after log back in world moved mouse to all items no crash

crash log:
https://paste.ee/p/ALlVn

**Comment by CubeTwo** [comment]
upd: 2d crash, was sorting inventory, and try to move backpack and its crashed. when crashed visually backpack was on slot where was before drag(highlighted slot on screenshoot), after login to world after crash it was moved to another slot 4 and dont crash anymore.
![2023-07-27_18 26 54](https://github.com/P3pp3rF1y/SophisticatedCore/assets/16674396/fcb60b67-3d75-46b9-97f2-8c6943dae06d)
crash log: 
https://paste.ee/p/S9Rgq

**Comment by P3pp3rF1y** [comment]
I have this fixed and trying to upload new releases to curseforge, but they seem to be having some issues with new uploads there. In the meantime you can grab latest release with the fix for your version here https://github.com/P3pp3rF1y/SophisticatedCore/packages/1386882/versions

**Comment by P3pp3rF1y** [comment]
this is fixed in the latest release of core on CF
