### ISSUE TITLE
Exception ticking world InventoryHandler.setSlotLimit

### ISSUE THREAD

**Issue by JoniLieh** [P3pp3rF1y/SophisticatedCore#156]
So I updated the SophisticatedCore Mod, restarted the server, went to my inventory to get to a different monitor, server crashed with this crash ↓
crash-log: [https://mclo.gs/Hyuw5ud](https://mclo.gs/Hyuw5ud)
(debug-log: [https://mclo.gs/9mve7le](https://mclo.gs/9mve7le))

Mb it's not bc of your mod, but your package is the only one in the crash log.

Edit: 
Just happend again, without being on the server, shutting down the entire server afterwards 
crash-log: https://mclo.gs/y2A6U7u
cutted debug-log: https://mclo.gs/QdfLxok

**Comment by P3pp3rF1y** [comment]
just updated backpacks to latest version and your issue is solved. Please always double check what versions you're using otherwise you will continue to run into issue like htis

**Comment by JoniLieh** [comment]
Oh, I am really sorry for that, guess I had backpacks still on an older version….
