### ISSUE TITLE
1.18.2- ctrl+q throws hand item if cursor over empty slot in sophisticated container

### ISSUE THREAD

**Issue by Aetherlight** [P3pp3rF1y/SophisticatedCore#157]
MC 1.18.2
FML 40.2.1

mod list:
sophisticatedcore-1.18.2-0.5.82.393
sophisticatedbackpacks-1.18.2-3.18.57.888
sophisticatedstorage-1.18.2-0.8.39.580
jei-1.18.2-forge-10.2.1.1005

a new curseforge instance. only changed video and sound settings. 
JEI was just so I could grab a backpack, barrel and chest while staying in survival mode 100% of the time.

1. put any item in hand 
2. open sophisticated backpack, barrel or chest (even backpack in hand!)
3. place cursor over any empty slot (inventory or container)
4. hold ctrl + q
5. item in hand is thrown

tested an iron oak barrel, iron oak chest, and a tier 1 backpack (both from hand and placed on ground) and it compared it to a vanilla chest to confirm it only happens with sophisticated storage/backpack.

**Comment by Aetherlight** [comment]
this bug is very inconsistent.  I removed JEI and reloaded the test world to be thorough and the issue seemed to go away. after messing around a bit it came back, so it is not JEI as I originally wrote in this comment.

here is a log of things I did until the bug happened.

1. (re)loaded world
2. tried oak barrel, no bug, closed
3.  tried oak iron chest, no bug, closed
4. tried barrel again, no bug, closed
5. opened vanilla chest, threw hotbar items while holding ctrl+q, closed
8. tried barrel again, no bug, closed
9.  _threw each item from hotbar with ctrl+q_ (no inventory open)
10. _picked them up_
11. opened barrel; **BUG PRODUCED**

-

1. reloaded world again from main menu
2. opened player inventory
3. threw all hotbar items (ctrl+q)
4. _picked up all items_
5. opened barrel **bug produced**

-

1. reloaded world
2. opened player inventory
3. shift+click items to inventory
4. closed inventory
5. opened barrel, no bug, closed barrel
6. threw a single stick (1 of 9) with just q.
7. opened barrel; no bug; closed
8. picked up the stick
9. opened barrel; no bug; closed
10. ctrl+q threw stack of sticks
11. opened barrel; no bug; closed
12. picked up the sticks
13. attempted barrel; no bug; closed
14. _ctrl+q threw multiple items_
15. _picked them up_
16. opened barrel; **BUG PRODUCED**

-

1. reloaded world
2. opened player inventory
3. _threw multiple items with ctrl+q held_
4. opened barrel; **BUG PRODUCED**


there, that seems to be how it happens. holding ctrl+q to throw items with either player inventory open or no inventory open will activate the bug until you reload. 

after more testing, I noticed that the bug only triggers after you PICK UP the items that had been thrown while holding ctrl+Q

**Comment by P3pp3rF1y** [comment]
This actually is I believe vanilla feature but usually requires holding  that key combination

**Comment by P3pp3rF1y** [comment]
Can you try with vanilla chest / barrel?

**Comment by Aetherlight** [comment]
I did try it with vanilla chest in both the initial report and the longer one where I tracked down how it happens. I will try a vanilla barrel though, and other containers/inventories like hopper, furnace, etc

**Comment by Aetherlight** [comment]
apparently this IS a vanilla bug which seems to have been "resolved"  in 1.19.3 (22w42a?) https://bugs.mojang.com/browse/MC-135973. it just manifests differently with sophisticated storage/backpacks by causing the hand item to be thrown.

I'm still hoping you can do something about the hand item being thrown though! if that were fixed, then your containers would effectively be immune to the bug! I totally understand if you don't want to bother with it though since it only effects older versions.

_Sophisticated_: Ctrl+Q+hold+drag WORKS fine in your containers until you reach an empty slot which it then causes the hand-item to be thrown.
_Vanilla_: Ctrl+Q+hold+drag is completely blocked from most containers once the bug is activated.

**Comment by P3pp3rF1y** [comment]
so yeah the drop happens inside vanilla code and I don't want to change that so I am closing this
