### ISSUE TITLE
Item icon rendering

### ISSUE THREAD

**Issue by CubeTwo** [P3pp3rF1y/SophisticatedCore#164]
**Describe the bug**
icons of item in shulker like inventories dont preview render in backpacks and player inventory
backpacks and storage affected
dont know if 1.19 and 1.20 affected
**To Reproduce**
1. Open backpack
2. mouseover to preview items in container
3. See error

**Expected behavior**
render icon of item on mouseover preview

**Screenshots**
![2023-09-05_12 03 26](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/16674396/71389f74-3be9-4aa8-9238-3bd53a957754)
![2023-09-05_12 03 34](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/16674396/6360500f-e87a-47c7-bdfc-219e5844aca5)
![2023-09-05_12 03 46](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/16674396/a5e6d801-d053-4834-810e-9b9e5d51bc51)
![2023-09-05_12 03 49](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/16674396/9362692b-1549-44a6-a66c-e3b9276b5b9f)

**Versions**
sophisticatedcore-1.18.2-0.5.87.416
sophisticatedbackpacks-1.18.2-3.18.60.906
sophisticatedstorage-1.18.2-0.8.42.599

**Comment by CubeTwo** [comment]
in storage icons dont render too
![2023-09-05_12 17 39](https://github.com/P3pp3rF1y/SophisticatedCore/assets/16674396/fdfac0c9-c5db-4a51-a6b5-0994f41aa8fb)

**Comment by P3pp3rF1y** [comment]
Fix for this is in latest release on curseforge
