### ISSUE TITLE
sophisticatedcore-1.20.1-0.5.89.425 on dedicated server

### ISSUE THREAD

**Issue by jpgtype** [P3pp3rF1y/SophisticatedCore#165]
Hi, I have a problem when running your mod on a dedicated server. The server crashes with an error:

```
Mod File: /root/minecraft/mods/sophisticatedcore-1.20.1-0.5.89.425.jar

        Failure message: Sophisticated Core (sophisticatedcore) encountered an error during the common_setup event phase

                java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER

        Mod Version: 0.5.89.425

        Mod Issue URL: https://github.com/P3pp3rF1y/SophisticatedCore/issues

        Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
```

**Comment by P3pp3rF1y** [comment]
You seem to have Item Borders mod on your server and that mod does not require to be there. I have fixed my compat with that to not register on server and will be releasing that fix soon, but you can just plain remove it from server and that will fix your issue in the meantime. Also please include the full crash log next time that actually shows it's crashing in that compat and would allow me to immediately advice you to remove the mod from server and only have it running on client.

**Comment by jpgtype** [comment]
Yeah, that was the problem, thanks.
I'll throw in a full crashlog next time.
