### ISSUE TITLE
Server crashing on launch 

### ISSUE THREAD

**Issue by TheMourningWolf** [P3pp3rF1y/SophisticatedCore#166]
This is a modpack that is fairly light so far and is crashing with sophisticated core
It did not produce a crash report but here is the server log file originally called latest.txt
[log.txt](https://github.com/P3pp3rF1y/SophisticatedCore/files/12694292/log.txt)

**Comment by P3pp3rF1y** [comment]
there's nothing wrong here with sophisticated mods you just seem to have another process using one of the files that the server needs to access so you will next to fix that on your side.
