### ISSUE TITLE
Server Crashes On Start Up

### ISSUE THREAD

**Issue by catsz** [P3pp3rF1y/SophisticatedCore#167]
I am running a dedicated server on a ubuntu linux machine and the server crashes anytime I try to load with sophisticated core. the crash log is attached.

[crash-2023-10-02_12.52.33-fml.txt](https://github.com/P3pp3rF1y/SophisticatedCore/files/12787383/crash-2023-10-02_12.52.33-fml.txt)

**Comment by P3pp3rF1y** [comment]
Just remove item borders mod from your server. I have this fixed to not try to load related stuff on server and will release that fix, but the mod is fully client side so there's no need for it on server.

**Comment by P3pp3rF1y** [comment]
Fix for this is in latest release on curseforge
