### ISSUE TITLE
Client Crash on mouseDragged event handler

### ISSUE THREAD

**Issue by KuryKat** [P3pp3rF1y/SophisticatedCore#168]
I am not sure what happened, but it has happened twice, it may be another mod causing it, but it happened while I was trying to place some tank upgrades in a backpack AND the Crash Report had a Stack of SophisticatedCore so I decided to report here

Here's the Crash Report: https://mclo.gs/V8tyDrl

And here is the FULL Latest log: https://mclo.gs/dlG0PTX

And here is the DEBUG log (who knows, might have something useful): https://mclo.gs/7TSFNVA

**Comment by P3pp3rF1y** [comment]
Ahh right your culprit is very likely biggerstacks as it transforms stuff in my code and I have no control over that so you would want to report this issue to them.

**Comment by KuryKat** [comment]
[Opened an Issue in their issue tracker](https://codeberg.org/PORTB/BiggerStacks/issues/26)
