### ISSUE TITLE
z fight

### ISSUE THREAD

**Issue by BlackAures1** [P3pp3rF1y/SophisticatedCore#177]
![image](https://github.com/P3pp3rF1y/SophisticatedCore/assets/43911230/ceed9848-9160-4e57-b535-00f0c1288a64)
![image](https://github.com/P3pp3rF1y/SophisticatedCore/assets/43911230/7749c77f-2c7d-4699-a9d6-213ca093580f)

sophisticatedcore-1.19.2-0.5.98.459.jar
sophisticatedstorage-1.19.2-0.8.47.625.jar

it has nothing to do with the texture pack. Other tabs work fine
![image](https://github.com/P3pp3rF1y/SophisticatedCore/assets/43911230/52d4384b-e010-472d-9669-f4aee6b765f3)

**Comment by P3pp3rF1y** [comment]
this is fixed in the latest release
