### ISSUE TITLE
Non-upgrade items in upgrade slots can crash the game

### ISSUE THREAD

**Issue by James103** [P3pp3rF1y/SophisticatedCore#19]
From https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/446:

> **Describe the bug**
> After Killing an enderman he droped a backpack with a diamond backpack inside and inside the diamond backpack there was diamond blocks in the filter upgrade slot upon klicking it it crashed the game
> 
> **To Reproduce**
> not been able to reproduce
> 
> **Crashlog**
> https://pastebin.com/5Uax6Pqb

Casting [any item] to IUpgradeItem here (should check that the item is actually a upgrade beforehand): https://github.com/P3pp3rF1y/SophisticatedCore/blob/9b49a4d8e08e366370eb2fd41ad21056909bb388/src/main/java/net/p3pp3rf1y/sophisticatedcore/common/gui/StorageContainerMenuBase.java#L1440

**Comment by P3pp3rF1y** [comment]
It's more of a bug that the diamond block ends up in the upgrade slot, it should never go in there, I will check why that is happening

**Comment by P3pp3rF1y** [comment]
In the latest version of sophisticated backpacks loot that gets generated in backpack will automatically exclude backpacks as that breaks a bit of balance given that they are put in backpack without inception upgrade and it also causes some of these super hard to fix issues. So this issue with latest version isn't possible
