### ISSUE TITLE
Crash when shift-clicking items out of any storage from sophisticated mods

### ISSUE THREAD

**Issue by Edvaize** [P3pp3rF1y/SophisticatedCore#196]
This is one of the strangest bugs I have ever seen lol.

As said in the title, when using a storage from your mods, sophisticated storage and backpacks, if you at some point hold shift and click an item slot to bring items into your inventory from the container, the game instantly crashes.

The crash report confirms that the only suspected mod is sophisticated core, and there is obviously some issue with the arrays.

Here is the entire crash report:
[crash-2024-01-19_21.13.59-client.txt](https://github.com/P3pp3rF1y/SophisticatedCore/files/13994258/crash-2024-01-19_21.13.59-client.txt)

**Comment by P3pp3rF1y** [comment]
Smoothswapping is the issue so you will need to remove that mod to not see these issues. They have issues like this logged for sophisticated and other mods but don't seem to care about fixing them.

**Comment by Edvaize** [comment]
Ohh, thank you mate, that makes so much sense actually. It's not a particularly important mod so I'm quite relieved that was the culprit
