### ISSUE TITLE
sophisticated backpacks error

### ISSUE THREAD

**Issue by JenniferDevelopez** [P3pp3rF1y/SophisticatedCore#197]
[29Jan2024 20:16:15.190] [Server thread/WARN] [sophisticatedcore/]: Too much loot to add to container. Overflow is voided.

**Comment by P3pp3rF1y** [comment]
Yeah that can happen if there is too much loot to add. Are you suggesting there isn't that much loot to add and there's actually a problem somewhere that it deletes loot when there's space? I would need to understand what backpack (what mob dropped it) was open / what the related loot table looks like.

**Comment by P3pp3rF1y** [comment]
closing given no follow up for quite a while
