### ISSUE TITLE
Crash when shift-clicking from a Sophisticated Storage chest.

### ISSUE THREAD

**Issue by koschanothere** [P3pp3rF1y/SophisticatedCore#198]
Playing with the Create+ modpack, if that matters. 

Sometimes, not sure exactly what the precursor is to the crash. But the immedeate cause is clear. Bug report gives an OOB error for sophisticated core.  Here's the bug report.
[crash-2024-02-02_11.26.26-client.txt](https://github.com/P3pp3rF1y/SophisticatedCore/files/14137351/crash-2024-02-02_11.26.26-client.txt)

Most often happens if i haven't opened the chest(s) for some time, but this is speculation. 
I'll try to understand it a little more myself but it's happened like 10 times already and I'm not too close to figuring it out.

**Comment by koschanothere** [comment]
Forgot to mention, both shift-clicking into and out of the chest may cause this. It's not 100% of the time too.

**Comment by P3pp3rF1y** [comment]
It is clear to me that- smooth swapping mod is broken and are not fixing their mod so until they fix it sophisticated is incompatible with that mod

**Comment by koschanothere** [comment]
Thanks a lot. Do you think there are any dependancies on smooth swapping? or is it alright to disable it? I've not been playing for too long and it's been doing more bad than good.

**Comment by P3pp3rF1y** [comment]
I don't play with it but every time this came up people just disabled smooth swapping and they were good
