### ISSUE TITLE
[Suggestion] Sorting by mods

### ISSUE THREAD

**Issue by drakray** [P3pp3rF1y/SophisticatedCore#216]
Hi, since the 561 update, sorting changed from RegistryName to EnglishTranslation.
Could it be possible to have a config to revert this, or a new sorting option to sort by mods please?
right now with this things are all over the place, and harder to manage

Thank you for your good work :D

**Comment by P3pp3rF1y** [comment]
Sorting by mod makes sense to me (it will likely use item name as secondary sort) so I will be adding that.

**Comment by drakray** [comment]
That would be perfect thanks :D

**Comment by P3pp3rF1y** [comment]
I implemented this a while back just forgot to close so closing now.
