### ISSUE TITLE
[1.19.2] Crash by Inventory Clicking

### ISSUE THREAD

**Issue by NikeSchuh** [P3pp3rF1y/SophisticatedCore#217]
Mod Version: sophisticatedcore-1.19.2-0.6.3.566.jar
Forge Version: 43.3.8

Sometimes when shift clicking certain slots the game crashes.

[crash-2024-03-16_11.16.53-client.txt](https://github.com/P3pp3rF1y/SophisticatedCore/files/14623215/crash-2024-03-16_11.16.53-client.txt)

**Comment by P3pp3rF1y** [comment]
Don't use smoothswapping, the mod is bugged like this and they are not fixing the issue for a very long time now.
