### ISSUE TITLE
shift click out of (kindof) the bottom half crashes the game

### ISSUE THREAD

**Issue by FOURLEAF-REP** [P3pp3rF1y/SophisticatedCore#242]
this didnt happen for like 3 days and is only happening now. i do have a lot of other mods but never had any problems until now. it seems to only happen in the bottom half of at least the diamond backpack. ive only had issues with this on 1.19.2 but may apply on other versions. if needed i can show with a video clip or in a call.

**Comment by P3pp3rF1y** [comment]
You have a crash log that you can share? And my guess would be that you have smooth swapping which is causing this crash

**Comment by FOURLEAF-REP** [comment]
i will get the log but i forgot i had that mod and i think you may have fixxed my problem so thank you in advance.

**Comment by FOURLEAF-REP** [comment]
[2024-06-07-5.log.gz](https://github.com/user-attachments/files/15749030/2024-06-07-5.log.gz)
idk if youll be able to read that or not

**Comment by P3pp3rF1y** [comment]
crash log would be better, but I can see that you have smooth swapping in there, just remove it and this should be fixed
