### ISSUE TITLE
Config settings -> Number of slots

### ISSUE THREAD

**Issue by DavidFlisar** [P3pp3rF1y/SophisticatedCore#243]
I don't know if this is a feature or not, but I have been looking for a way to limit the number of rows and columns displayed so that it doesn't overlap the existing JEI search. Any idea how to do that or any alternative?

**Comment by DavidFlisar** [comment]
The overlapping occurs only if there is a scroll, otherwise on a single chest without scroll it works fine

**Comment by P3pp3rF1y** [comment]
could you show me a screenshot of that? I am pretty sure that this works correctly with just sophisticated and JEI

**Comment by DavidFlisar** [comment]
I mean I did fix it somehow. Instead of configuring the sophisticated, I just changed the search placement. Let me just change the config to show you how it looked like.
![image](https://github.com/P3pp3rF1y/SophisticatedCore/assets/103906247/3e08af76-2cd8-4b26-ab3c-c3f9958ff39d)
This first screenshot is how it looks now. Otherwise it looked like this:
![image](https://github.com/P3pp3rF1y/SophisticatedCore/assets/103906247/70739f76-7cc3-4ee7-9e99-a1b3397bb43b)

**Comment by P3pp3rF1y** [comment]
Oh you mean overlap at the bottom with the search box? I assumed you mean overlap on the right

**Comment by P3pp3rF1y** [comment]
I will likely need to add something to the jei integration to let it know the GUI is extending that far to the bottom

**Comment by DavidFlisar** [comment]
Oh alright seems fair. It doesn't need to be fixed fast if it takes a lot of time, in the meantime I have the search on the right side. Also thank you for helping, you are an awesome developer

**Comment by P3pp3rF1y** [comment]
this actually turned out to be an issue in JEI where it didn't move the search bar out of the place of gui. In 1.21 this is fixed.
