### ISSUE TITLE
Experience should have associated bucket item

### ISSUE THREAD

**Issue by clarfonthey** [P3pp3rF1y/SophisticatedCore#245]
Essentially, the lack of a bucket of experience makes it difficult to store the experience used by this mod in other mods, like Refined Storage. Since Refined Storage requires using a bucket to remove fluids directly from storage or to add filters on exporters, not having a bucket effectively prevents the experience fluid used by this mod from working with those other mods.

Additionally, it's not really feasible to ensure your storage always contains the experience from a different mod, because while it will be compatible, emptying the storage of experience and then adding some back will always use the SophisticatedCore version of the fluid.

**Comment by P3pp3rF1y** [comment]
Are you not able to use something like jei to drag the experience fluid over to refined storage filter?

**Comment by clarfonthey** [comment]
Unfortunately not for fluids, with refined storage at least. It's kind of clunky.

**Comment by P3pp3rF1y** [comment]
Added this in 1.21 so it's available from there on. I don't feel this is critical enough to add in any of the previous versions.

**Comment by Gatoluche** [comment]
Hey there!
Could I suggest indeed adding this to previous versions like 1.20?
1.20 seems to the version many popular mods are currently stuck in, and while I understand this doesn't seem critical on a first look,
the biggest problem that this brings is that it's not immediately obvious that it will be an issue, so it can result in getting considerable amounts of experience stuck inside a Refined Storage system, which you cannot get out by any means short of using other mods to turn the experience into enchanting bottles (which is inconvenient, often inefficient and burns a lot of glass).
