### ISSUE TITLE
[BUG] Sophisticated Core slots missing

### ISSUE THREAD

**Issue by ThatFoxgirl** [P3pp3rF1y/SophisticatedCore#247]
I have a bug on where I cannot see the function from Sophisticated Core in my inventory to equip my Backpack on a certain Backpack slot. I don't know what's causing this, I have both newest Versions for Forge 1.20.1
![image_2024-07-19_132320918](https://github.com/user-attachments/assets/b36b97b4-2c8b-4f24-a804-bc74a487410b)
![image_2024-07-19_132413712](https://github.com/user-attachments/assets/8196b4c1-2bdb-4cd6-b936-5760addbabcd)

**Comment by P3pp3rF1y** [comment]
you have curios api installed? that only works with curios api

**Comment by ThatFoxgirl** [comment]
That was the issue. Now it works, thank you!
