### ISSUE TITLE
enhancement : max stack before compression

### ISSUE THREAD

**Issue by McKitten** [P3pp3rF1y/SophisticatedCore#258]
You have support for AllTheCompressed and the advanced/compacting upgrade but i was hoping for another button added to its settings. 
All to often the upgrade will see 10 and will make 1+1 taking up more space, I was hoping the button would prevent the x+1 from happening until the stack hits its maximum. So in the case of iron it would take 65 for a new stack to be formed,
The other alternative would be a new economy upgrade with the compression and stack upgrades combined at lvl 1 of the mod and then upgradable to lvl 2. 

Thank you for your work on this mod. It is pawesome! (I refused to play atm10 until i was added) and GL.

**Comment by P3pp3rF1y** [comment]
I am guessing that you want to have a stack of uncompressed available and Storage compression upgrade already does that. I don't aim to make changes to Compacting upgrade so closing this one. Also no plan to combine upgrades together to save upgrade slot space
