### ISSUE TITLE
JEI and Core Version

### ISSUE THREAD

**Issue by shaundacat** [P3pp3rF1y/SophisticatedCore#274]
When booting it says sophisticatedcore needs jei version 15.9 and jei 15.9 does not exist.

**Comment by shaundacat** [comment]
![Screenshot 2024-09-22 170741](https://github.com/user-attachments/assets/66c6b502-f1ac-4195-9f5c-e8e324cad57a)

**Comment by IsPongeCry** [comment]
with me too

**Comment by IsPongeCry** [comment]
![image](https://github.com/user-attachments/assets/15964286-2a8c-4c5e-83df-eef8eb1a9650)
![image](https://github.com/user-attachments/assets/b3e2c3c8-1d72-4d78-b747-437676d7a340)
![image](https://github.com/user-attachments/assets/568d67be-8604-4ab8-8a7d-dda059ed3fb5)

**Comment by IsPongeCry** [comment]
Well, now it's started
![image](https://github.com/user-attachments/assets/d60e1472-21eb-49ac-b07c-41930fb144e3)

**Comment by P3pp3rF1y** [comment]
Have you actually checked downloads before posting this issue? 15.19 version is 5 days old by now and there are also multiple versions after

**Comment by shaundacat** [comment]
curseforge didnt say so
