### ISSUE TITLE
[BUG] [CRASH] Description: mouseReleased event handler - 1.20.1

### ISSUE THREAD

**Issue by muggleorwizard** [P3pp3rF1y/SophisticatedCore#286]
Sophisticated Core: 1.20.1-0.6.33.711
JEI: jei-1.20.1-forge-15.19.0.89

Game crashes when using the plus sign to move a recipe from JEI into the crafting area of a backpack.

Crash Log: https://pastebin.com/vnpYq4xs

Seems to be a similar error to this issue, but not resolved: https://github.com/P3pp3rF1y/SophisticatedCore/issues/271

**Comment by P3pp3rF1y** [comment]
You need to update your JEI. The issue you're seeing is the exact opposite of the one in #271 . There the issue was that new version of JEI made a change that caused the integration to break, I made a change that fixed that, but you are using old version that is incompatible with that fix
