### ISSUE TITLE
Crash on launch - java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by bl1te** [P3pp3rF1y/SophisticatedCore#289]
[crash-2024-10-12_22.53.22-fml.txt](https://github.com/user-attachments/files/17351303/crash-2024-10-12_22.53.22-fml.txt)
`java.util.ConcurrentModificationException`
The game sometimes randomly crashes with this error message. Sometimes it boots up just fine (no crash).

MC Java 1.21.1
Neoforge 21.1.68
Sophisticated Core 1.21-0.6.44.719 (though happens in recent versions as well).

**Comment by P3pp3rF1y** [comment]
I fixed this a few days after the report, but forgot to close. So just use the latest release and you're good
