### ISSUE TITLE
[1.19] Sophisticated Core (sophisticatedcore) has failed to load correctly

### ISSUE THREAD

**Issue by Baggytrousers27** [P3pp3rF1y/SophisticatedCore#29]
41.0.96

java.lang.InvocationTargetException: null

[Crashlog](https://pastebin.com/te9MVKfj)

**Comment by P3pp3rF1y** [comment]
please make sure that you update before reporting a bug like this - this bug was already fixed by the time of your report

**Comment by Baggytrousers27** [comment]
No joke, my calendar says this issue was posted exactly 5 minutes before sophisticatedcore-1.19-0.3.9.63.jar was live (Although my time zone calculations may be off).
¦D
Will still keep an eye out in future just in case.
