### ISSUE TITLE
[BUG] Game ocassionally crashes when opening backpack

### ISSUE THREAD

**Issue by dgl888** [P3pp3rF1y/SophisticatedCore#291]
Hello, 
I recently added sophisticated backpacks to a modpack I was using (Stoneblock 3). When I remove the mod, I no longer have the issue.
When opening backpacks, the game will ocassionally crash with this log:
[crash-2024-10-14_19.29.00-client.txt](https://github.com/user-attachments/files/17370327/crash-2024-10-14_19.29.00-client.txt)

Any solutions for this error?

**Comment by P3pp3rF1y** [comment]
That is an REI crash all I can see that I am doing from my side is event as part of screen rendering which is going to happen for all more or less standard screens. So you will need to report this to REI
