### ISSUE TITLE
Crash with Jei and Sophisticated Core 1.19.2

### ISSUE THREAD

**Issue by Wolfcvz** [P3pp3rF1y/SophisticatedCore#292]
[crash-2024-10-20_19.19.30-client.txt](https://github.com/user-attachments/files/17453211/crash-2024-10-20_19.19.30-client.txt)

**Comment by P3pp3rF1y** [comment]
I am no longer supporting 1.19.2 with nothing but critical fixes so you will need to downgrade jei to a version that hasn't changed like this. I believe the change was 2 months ago.

**Comment by ModernGamingWorld** [comment]
@P3pp3rF1y The only issue I see with this is if a mod in, say, someone's modpack requires the New JEI. They are going to have to update to said new JEI. Not telling you what to do, but I would at least suggest fixing the JEI issues on 1.19.2, as other mod developers are going to require it for some of their mods and people like me, DexxKnight, and others with big modpacks can't just downgrade without having major issues

**Comment by P3pp3rF1y** [comment]
fyi, released a fix for this yesterday so just download the latest core and you should be good
