### ISSUE TITLE
Stack count tooltip broken

### ISSUE THREAD

**Issue by brisingraerowing** [P3pp3rF1y/SophisticatedCore#3]
![2022-05-13_15 07 52](https://user-images.githubusercontent.com/250409/168373716-72a9da93-f095-4e12-80ef-f62d198b9f42.png)

I'm putting this here as both mods are broken. This might be a conflict.

**Comment by P3pp3rF1y** [comment]
fixed in the latest version on curseforge, just make sure you update storage as well as it's not compatible with previous versions of storage
