### ISSUE TITLE
Index out of bounds crash on 1.21.1-0.6.47.728

### ISSUE THREAD

**Issue by michael-hart** [P3pp3rF1y/SophisticatedCore#303]
Had a server crash on ATM10 pack with Sophisticated Core version 1.21.1-0.6.47.728. I only have the crash report and hoped it would be useful. If it's not enough info, please let me know what else would help and I can try to get it.

Crash report attached!

[crash-2024-11-05_08.45.06-server.txt](https://github.com/user-attachments/files/17630323/crash-2024-11-05_08.45.06-server.txt)

I hope it helps!

**Comment by P3pp3rF1y** [comment]
Only got to this now. I feel like this is something I already fixed where it didn't properly update number of slots when storage was upgraded. So I would definitely need more info on how I can recreate to at least be able to double check that the issue is really gone.

**Comment by mikelikesrobots** [comment]
I'm afraid I don't have any more info. It might well be an issue you have already fixed. If it's not enough info, better to close it.

**Comment by michael-hart** [comment]
Woops, replied from the wrong account. Explains why I couldn't close the issue!
