### ISSUE TITLE
Compatibility problem between Spice of Life Carrot edition and Sophisticated Backpacks

### ISSUE THREAD

**Issue by gaminggirl** [P3pp3rF1y/SophisticatedCore#309]
Compatibility problem between Spice of Life Carrot edition and Sophisticated Backpacks after release of sophisticatedcore-1.20.1-0.6.35.726.jar

Until that version released ths Spice of Life book counted up when one ate food, after this update it only counts up if eating from inventory. 

Solcarrot edition: solcarrot-1.20.1-1.15.1
Minecraft edition: 1.20.1

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest release on CF
