### ISSUE TITLE
Issues with Sophisticated Core in Minnecraft 1.20.1 modpack

### ISSUE THREAD

**Issue by mauuuuuuuu** [P3pp3rF1y/SophisticatedCore#340]
Hello,
After updating mods in my modpack some weeks ago I am facing crash issues. It seems to be related to Sophisticated core and Create and a third mod. Whenever I am deactivating them it works again. 

I am on Minecraft 1.20.1, Forge 0.16.9 and also tried 0.16.7.

I have the error script with exit code 1.

[crash-2024-12-07_23.03.22-client.txt](https://github.com/user-attachments/files/18050018/crash-2024-12-07_23.03.22-client.txt)

**Comment by mauuuuuuuu** [comment]
I can't seem to revert the mod versions as they were before to fix the problem which is weird. Sadly I can't be sure which versions I had when everything worked fine.

**Comment by P3pp3rF1y** [comment]
You seem to be trying to run this forge mod on fabric, that's not going to work as it's not made for Fabric. Either remove it or switch over to forge. Or you may have been using the unofficial fabric version but in that case you need to report it on the its own issue tracker.

**Comment by mauuuuuuuu** [comment]
Oh yes I am on the unofficial forge version. Thank you I will try with them. Am 08.12.2024 00:12 schrieb P3pp3rF1y ***@***.***>:
You seem to be trying to run this forge mod on fabric, that's not going to work as it's not made for Fabric. Either remove it or switch over to forge. Or you may have been using the unofficial fabric version but in that case you need to report it on the its own issue tracker.
