### ISSUE TITLE
SophCore Incompatibility.

### ISSUE THREAD

**Issue by GrimWolf47** [P3pp3rF1y/SophisticatedCore#45]
I was trying to play with my personally made modpack for 1.19.2 using forge 43.1.3, I was getting a crash I couldn't figure out, learned it was a incompatibility, seems SophCore and I Like Wood, don't agree with each other because when I went to make a world the game would crash and claim this "sophisticatedcore-common.toml: The process cannot access the file because it is being used by another process" but the files were not open anywhere to my knowledge so I was confused, but after removing "I like wood" and its BYG and Twilight Forest addons I was able to play again.

Mod Versions
sophisticatedcore-0.5.9.117

sophisticatedbackpacks-3.18.24.703
sophisticatedstorage-0.5.12.138

Crashlog, Idk if its needed here but I'll put it here anyways.
[crash-2022-09-02_01.57.00-client.txt](https://github.com/P3pp3rF1y/SophisticatedCore/files/9475782/crash-2022-09-02_01.57.00-client.txt)

**Comment by P3pp3rF1y** [comment]
I don't know how to recreate this crash. Also those versions don't exist on curseforge so either you have redacted them or they were not downloaded from official location. Please make sure that you download from curseforge only.

And as for the crash - sophisticated backpacks even in 1.19.2 is used by so many modpacks that it would be surprising that this was an issue in sophisticated backpacks. Something is trying to load the config or is changing how forge config stuff works so I would suggest reporting to the mods that you have to remove to make this work. If they find out something wrong with my implementation feel free to let me know.

**Comment by GrimWolf47** [comment]
> I don't know how to recreate this crash. Also those versions don't exist on curseforge so either you have redacted them or they were not downloaded from official location. Please make sure that you download from curseforge only.
> 
> And as for the crash - sophisticated backpacks even in 1.19.2 is used by so many modpacks that it would be surprising that this was an issue in sophisticated backpacks. Something is trying to load the config or is changing how forge config stuff works so I would suggest reporting to the mods that you have to remove to make this work. If they find out something wrong with my implementation feel free to let me know.

I downloaded the mods off the Curseforge app, I might've mistyped the version so that's my bad. I can't figure out what would be messing with configurations or how they work, I originally had the same thought and removed the only two mods that I knew messed with Configs those being Mrcrayfishes Configured and Catlogue but there was no change in my issue, issue only stopped after I removed the "I like wood" mod along with its BYG and Twilight Forest add-ons. Either way I hope you have a great day!

**Comment by papillo12** [comment]
I have the same bug currently
[crash-2022-10-18_20.35.29-client.txt](https://github.com/P3pp3rF1y/SophisticatedCore/files/9816409/crash-2022-10-18_20.35.29-client.txt)
[crash-2022-10-18_20.41.38-client.txt](https://github.com/P3pp3rF1y/SophisticatedCore/files/9816410/crash-2022-10-18_20.41.38-client.txt)
[crash-2022-10-18_20.31.54-client.txt](https://github.com/P3pp3rF1y/SophisticatedCore/files/9816411/crash-2022-10-18_20.31.54-client.txt)

**Comment by P3pp3rF1y** [comment]
closing as I was never able to recreate and haven't seen any new reports either
