### ISSUE TITLE
crashing if use sophisticatedcore-1.18.2-0.1.0.19

### ISSUE THREAD

**Issue by CubeTwo** [P3pp3rF1y/SophisticatedCore#5]
updated sophisticatedcore from sophisticatedcore-1.18.2-0.0.7.16 to sophisticatedcore-1.18.2-0.1.0.19  and cant generate new world game crashing

log: https://paste.ee/p/kOkOn

**Comment by P3pp3rF1y** [comment]
you need to read the changelog which specifically refers to a need of using new versions of backpacks and storage which haven't been released yet. Unfortunately for the build process I need to make new version of core with breaking changes public a little earlier than the other two can release and you have just downloaded this during that time

**Comment by P3pp3rF1y** [comment]
closing this as new version of backpacks is already live and storage will be shortly

**Comment by border999** [comment]
This was closed two days ago, I'm using sophisticatedcore-1.18.2-0.1.0.19 and sophisticatedbackpacks-1.18.2-3.16.1.579. I'm crashing moments into starting up the game.

**Comment by border999** [comment]
[debug.log](https://github.com/P3pp3rF1y/SophisticatedCore/files/8717377/debug.log)

**Comment by P3pp3rF1y** [comment]
@border999 I don't see any issue in that log - you have a crash log or something that would show me the issue that you have?

**Comment by border999** [comment]
Ignore me, bad wither was pitching a fit. Updated that and can now start the game. Will test opening a world now
