### ISSUE TITLE
crash 1.19.2

### ISSUE THREAD

**Issue by papillo12** [P3pp3rF1y/SophisticatedCore#52]
the game crashes on opening and always tells me it's sophisticatedcore 
[crash-2022-10-23_15.17.32-fml.txt](https://github.com/P3pp3rF1y/SophisticatedCore/files/9848306/crash-2022-10-23_15.17.32-fml.txt)
[crash-2022-10-23_15.32.12-client.txt](https://github.com/P3pp3rF1y/SophisticatedCore/files/9848307/crash-2022-10-23_15.32.12-client.txt)
[crash-2022-10-23_20.01.43-fml.txt](https://github.com/P3pp3rF1y/SophisticatedCore/files/9848308/crash-2022-10-23_20.01.43-fml.txt)
[crash-2022-10-23_20.13.45-fml.txt](https://github.com/P3pp3rF1y/SophisticatedCore/files/9848309/crash-2022-10-23_20.13.45-fml.txt)
[crash-2022-10-23_20.15.25-client.txt](https://github.com/P3pp3rF1y/SophisticatedCore/files/9848310/crash-2022-10-23_20.15.25-client.txt)

**Comment by papillo12** [comment]
![Captura de pantalla 2022-10-23 203552](https://user-images.githubusercontent.com/80440525/197437575-66eb528a-bf9c-4067-b195-036e6c2849b1.png)

**Comment by papillo12** [comment]
when I removed all the Sophisticated mods the game was fixed

**Comment by papillo12** [comment]
but also, first it tells me that it could not start well likewood, then I remove that mod and only comes out a normal crash that I associate to Sophisticatedcore, then I remove the modelfix mod and the mod notenoughcrashes already tells me that it is Sophisticated core.

**Comment by papillo12** [comment]
I just downgraded to sophisticatedcore-1.19.2-0.5.12.130.jar and the game no longer crashes

**Comment by P3pp3rF1y** [comment]
latest version of core has a fix for this crash

**Comment by papillo12** [comment]
it no longer crashes at startup but I had to downgrade again to sophisticatedcore-1.19.2-0.5.12.130 because the world I have says that the datapacks do not load well and makes me start it in safe mode and if I want to create a new world the game crashes, doing the downgrade I have no problems.

**Comment by P3pp3rF1y** [comment]
could you share the actual error you're seeing regarding the datapacks?

**Comment by papillo12** [comment]
![imagen_2022-10-24_150217971](https://user-images.githubusercontent.com/80440525/197628698-4cee7673-918e-4623-bb4b-20c56714c95b.png)

**Comment by papillo12** [comment]
https://crashy.net/issc0n4s4Sp2jccFFsTP

[crash-2022-10-24_15.02.33-client.txt](https://github.com/P3pp3rF1y/SophisticatedCore/files/9855344/crash-2022-10-24_15.02.33-client.txt)

**Comment by papillo12** [comment]
[latest.log](https://github.com/P3pp3rF1y/SophisticatedCore/files/9855349/latest.log)
