### ISSUE TITLE
[1.18.2]java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "itemNames" is null

### ISSUE THREAD

**Issue by OcrSu** [P3pp3rF1y/SophisticatedCore#53]
10/24/2022
sophisticatedcore-1.18.2-0.5.15.137.jar

Win11 X64 Java17
[crash-2022-10-24_12.47.47-client.txt](https://github.com/P3pp3rF1y/SophisticatedCore/files/9848805/crash-2022-10-24_12.47.47-client.txt)

**Comment by P3pp3rF1y** [comment]
fixed in the latest release
