### ISSUE TITLE
Crash from sophisticatedcore

### ISSUE THREAD

**Issue by ItsChase7** [P3pp3rF1y/SophisticatedCore#54]
When loading up the modpack Mechanical Mastery it crashes 30 sec after I launch it, I played in yesterday and it worked completely fine. The first line in the crash is:  net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file sophisticatedcore-client.toml of type CLIENT for modid sophisticatedcore. I will link the whole thing. Pls help
[crash-2022-10-24_19.16.31-client.txt](https://github.com/P3pp3rF1y/SophisticatedCore/files/9856118/crash-2022-10-24_19.16.31-client.txt)

**Comment by P3pp3rF1y** [comment]
This was probably caused by inconsistent data in soph core config file. I would suggest just deleting `sophisticatedcore-common.toml` and restarting

**Comment by P3pp3rF1y** [comment]
closing given that this is stale
