### ISSUE TITLE
random crash on 1.18.2

### ISSUE THREAD

**Issue by CrazyDev05** [P3pp3rF1y/SophisticatedCore#55]
version: 0.5.15.141
fml: 40.1.84
[crash-2022-11-01_13.52.00-server.txt](https://github.com/P3pp3rF1y/SophisticatedCore/files/9910199/crash-2022-11-01_13.52.00-server.txt)

**Comment by phrostt** [comment]
Have a similar issue, but with player.
https://pastebin.com/3YkhdTKS

**Comment by P3pp3rF1y** [comment]
I made a fix and added a bit of logging to prevent this and log where it still gets into an inconsistent state

**Comment by P3pp3rF1y** [comment]
And actually I meant to add this is available in the latest releases on curseforge
