### ISSUE TITLE
Crashes running on 1.19

### ISSUE THREAD

**Issue by ModifiedMC** [P3pp3rF1y/SophisticatedCore#56]
Hello, I have been trying out options trying to replace sophisticated bags/storage for the other bags and iron chests in my pack and I can't get it to run.

I've tried removing mods suggested by Yummy (VTweaks, and ftb-backups), ive tried cleaning out the config folder, and also changing the forge version.

here is the pastebin Yummy said would be helpful :[https://pastebin.com/FuXzZtUg]( https://pastebin.com/FuXzZtUg)

**Comment by ModifiedMC** [comment]
updated with crash report (https://pastebin.com/R41TYc61) with another version of my pack running all mods and no vtweaks - so it must be an incompatibility with a few mods then.

**Comment by P3pp3rF1y** [comment]
the first one is vtweaks doing some funky stuff where it tries to load JEI compatibility code even though JEI isn't in the pack. The second one is related to config being blocked by some other process which seems to be related to curseforge launcher causing it (at least that's what I found after quite a bit of figuring out of the issue where some FTB modpacks have this issue with curseforge as well but work properly in other launchers). So I would suggest using different launcher first and see if the issue gets resolved.

**Comment by P3pp3rF1y** [comment]
Have you had any luck using a different launcher?

**Comment by P3pp3rF1y** [comment]
closing given no response
