### ISSUE TITLE
Create the game world, crash

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/SophisticatedCore#74]
[crash-2023-02-01_11.23.57-client.txt](https://github.com/P3pp3rF1y/SophisticatedCore/files/10553024/crash-2023-02-01_11.23.57-client.txt)
[latest.log](https://github.com/P3pp3rF1y/SophisticatedCore/files/10553027/latest.log)

**Comment by ghost** [comment]
![QQ图片20230201113158](https://user-images.githubusercontent.com/83486178/215938596-0c796d39-7ab5-4974-ac52-67bbdd6f37bb.png)

**Comment by ghost** [comment]
This happens the first time a mod is loaded

**Comment by P3pp3rF1y** [comment]
What launcher do you use? This seems to happen specifically with curseforge launcher which for some reason blocks config files and then changes to them crash the game

**Comment by P3pp3rF1y** [comment]
closing given no response
