### ISSUE TITLE
Server freezing,  timing everyone out

### ISSUE THREAD

**Issue by jaynotgay** [P3pp3rF1y/SophisticatedCore#77]
IntegratedDynamics-1.19.2-1.16.2 All the mods 8
![image](https://user-images.githubusercontent.com/30220126/227713235-7338417c-a6a4-4115-8eb8-4a5e1cf20072.png)

**Comment by P3pp3rF1y** [comment]
This is not helpful at all, I have no idea what's running there, if you can share link to the spark result I may be able to tell you more

**Comment by P3pp3rF1y** [comment]
closing given no response
