### ISSUE TITLE
Server config does not remove craftability of items (1.18.2)

### ISSUE THREAD

**Issue by The-Math-Fish** [P3pp3rF1y/SophisticatedCore#84]
Short version: Disabling an item (in this case, sophisticated storage chests and their upgraded versions) in the sophisticated storage server config does not keep a player from crafting the item if they happen to know the recipe.

Long version:
Here are the versions of the most relevant mods mentioned below:

CraftTweaker-forge-1.18.2-9.1.207
ExtendedCrafting-1.18.2-4.1.2
jei-1.18.2-9.7.1.255
JEITweaker-1.18.2-3.0.0.9
sophisticatedbackpacks-1.18.2-3.18.43.802
sophisticatedcore-1.18.2-0.5.46.233
sophisticatedstorage-1.18.2-0.6.22.308

I currently am working on a little modpack for myself and wanted to disable all recipes for upgrades in sophisticated storage and replace the recipes with custom ones. The difficulty was figuring out how to disable just the recipes. I wasn't able to find a way to do that as crafttweaker doesn't interact with the colored chests (jei doesn't recognize colored recipes) and the sophisticated core config removes both the appearance and recipes of items in jei. However, in testing if the items could be crafted (in this case light blue netherite chest, white gold chest, and oak chest), I found that all chests could still be crafted despite being disabled. And yes, I did a full reset after changing and saving the config file. I currently have all the default settings for sophisticated storage, sophisticated backpacks, and sophisticated core except for the following in the sophisticated core server config:

"sophisticatedstorage:chest|false", "sophisticatedstorage:iron_chest|false", "sophisticatedstorage:gold_chest|false", "sophisticatedstorage:diamond_chest|false", "sophisticatedstorage:netherite_chest|false"

I spot-checked everything in jei and found that all these chests were not visible in jei (good) and the recipes could not be looked up with jei (good) but the items could still be crafted using the original recipes (bad). I simply typed "chest", "iron chest", etc for visibility in jei. I looked up a random netherite chest and diamond chest in jei to check if the recipes showed. I checked the light blue netherite chest, white gold chest, and oak chest to see if the items could be crafted in both creative mode and survival mode. In all cases I was able to craft the item in a vanilla crafting table and extended crafting's basic crafting table.

I hope this is enough information. I can provide some screenshots if needed.

**Comment by The-Math-Fish** [comment]
I'm not sure if I should open a separate issue for this or not, but it is closely related to the above so ...

With the same setup as above, I noticed upon further testing that the recipes for the basic chests and the dyeing recipes are not removed from jei either.

Example recipes:
sophisticatedstorage:oak_chest_from_vanilla_chest
sophisticatedstorage:oak_chest
sophisticatedstorage:single_color_white (and all other colors)

I also had a crafttweaker script that is meant to remove all the upgrade recipes (forgot the base ones XD). Crafttweaker gave me warning messages that none of the recipes exist, though I can still craft them if I put the ingredients in a crafting table or smithing table. Here is my crafttweaker log. Skip to lines 146-169 and 253-260.
[crafttweaker.log](https://github.com/P3pp3rF1y/SophisticatedCore/files/11149705/crafttweaker.log)

**Comment by P3pp3rF1y** [comment]
Fix for this is in latest release on curseforge
