### ISSUE TITLE
Storage Migration

### ISSUE THREAD

**Issue by Dr-WeiAL** [P3pp3rF1y/SophisticatedCore#93]
Is it possible to add a storage migration function to a storage that has a large number of items in it but wants to change a location for it, which is a pain?
Meaning migrate all items in a slot to another slot in the current storage

![image](https://user-images.githubusercontent.com/47446553/234356207-f12dcd5a-8112-4c8a-9cdf-861f30031517.png)

**Comment by P3pp3rF1y** [comment]
This is possible now that sorting prefers memorized slots - you can just remove slot memory from the current stacks place and remember it somewhere else and then sort to get the stack moved
